# Generated by Django 4.0.4 on 2022-04-24 09:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Postmsg',
        ),
        migrations.RenameModel(
            old_name='Searches',
            new_name='Search',
        ),
    ]
