# Generated by Django 4.0.4 on 2022-04-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_posts_postmsg_rename_searches_search'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workname',
            new_name='occupations',
        ),
    ]
