# Generated by Django 4.0.4 on 2022-04-24 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_rename_workname_occupations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='host',
        ),
        migrations.AddField(
            model_name='search',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
