# Generated by Django 4.0.4 on 2022-04-24 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_remove_search_host_search_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='host',
        ),
        migrations.AddField(
            model_name='search',
            name='searcheduser',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
