# Generated by Django 4.0.4 on 2022-04-25 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_search_host_search_searcheduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='numberofserviceproviders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('workname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.occupations')),
            ],
        ),
    ]
